# Generated by Django 3.0.7 on 2020-06-18 11:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=32)),
                ('registration_status', models.BinaryField()),
                ('customer_address', models.CharField(max_length=128)),
                ('customer_contact', models.CharField(max_length=16)),
                ('customer_gender', models.CharField(blank=True, choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHER')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=32)),
                ('item_stock', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('item_title', models.CharField(max_length=64)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_company', models.CharField(max_length=32)),
                ('item_discount', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='ItemBatch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_date', models.DateField()),
                ('batch_expiry', models.DateField()),
                ('batch_quantity', models.IntegerField()),
                ('batch_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='irsapi.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=32)),
                ('category_discount', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField()),
                ('order_discount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='irsapi.Customer')),
                ('signed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Random',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=32)),
                ('item_stock', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_key', models.IntegerField()),
                ('creation_date', models.DateField()),
                ('store_title', models.CharField(max_length=64)),
                ('store_location', models.CharField(max_length=128)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salepoint',
            fields=[
                ('salepoint_id', models.AutoField(primary_key=True, serialize=False)),
                ('salepoint_key', models.IntegerField()),
                ('salepoint_status', models.BinaryField()),
                ('salepoint_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='irsapi.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sale_discount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('sale_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='irsapi.ItemBatch')),
                ('sale_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='irsapi.Item')),
                ('sale_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='irsapi.Order')),
            ],
        ),
        migrations.AddField(
            model_name='itembatch',
            name='batch_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='irsapi.Store'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='irsapi.ItemCategory'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=32)),
                ('date_of_joining', models.DateField()),
                ('employment_status', models.BinaryField()),
                ('designation', models.CharField(choices=[('A', 'ADMIN'), ('M', 'MANAGER'), ('C', 'CASHIER')], max_length=16)),
                ('employee_age', models.IntegerField()),
                ('pay_grade', models.IntegerField()),
                ('hired_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
