# Generated by Django 3.0.7 on 2020-06-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irsapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Random',
        ),
    ]
