# Generated by Django 3.0.7 on 2020-06-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irsapi', '0003_auto_20200618_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='category_discount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
