# Generated by Django 3.0.3 on 2020-02-16 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('irsapi', '0005_auto_20200216_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2020, 2, 16, 14, 29, 59, 517974, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 14, 29, 59, 519968, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='store',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 16, 14, 29, 59, 516975, tzinfo=utc)),
        ),
    ]
