# Generated by Django 3.0.3 on 2020-03-04 22:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('irsapi', '0008_auto_20200305_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2020, 3, 4, 22, 32, 42, 689666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 22, 32, 42, 705286, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='store',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 4, 22, 32, 42, 689666, tzinfo=utc)),
        ),
    ]
