# Generated by Django 3.0.3 on 2020-03-04 22:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('irsapi', '0009_auto_20200305_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(default=datetime.datetime(2020, 3, 4, 22, 36, 12, 623918, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itembatch',
            name='batch_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='irsapi.Item'),
        ),
        migrations.AlterField(
            model_name='itembatch',
            name='batch_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='irsapi.Store'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 22, 36, 12, 639539, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='irsapi.Order'),
        ),
        migrations.AlterField(
            model_name='salepoint',
            name='salepoint_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='irsapi.Store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 4, 22, 36, 12, 623918, tzinfo=utc)),
        ),
    ]
